data:
  - attributes:
      created_at: '2023-01-17T16:31:38'
      destination_override_endpoint: >-
        https://echo.apps.verygood.systems
      entries:
        - classifiers: {}
          config:
            condition: AND
            rules:
              - expression:
                  field: PathInfo
                  operator: matches
                  type: string
                  values:
                    - /post
              - expression:
                  field: ContentType
                  operator: equals
                  type: string
                  values:
                    - application/json
          id: f4ff1eef-8ab1-4219-987d-befc517313fd
          id_selector: null
          operation: REDACT
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.account_number
          transformer_config_map: null
        - classifiers: {}
          config:
            condition: AND
            rules:
              - expression:
                  field: PathInfo
                  operator: matches
                  type: string
                  values:
                    - /post
          id: fc8564c9-c189-4cdd-b031-a6b8e47f23f9
          id_selector: null
          operation: REDACT
          operations: null
          phase: REQUEST
          public_token_generator: ALPHANUMERIC_SIX_T_FOUR
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.card-number
          transformer_config_map: null
        - classifiers: {}
          config:
            condition: AND
            rules:
              - expression:
                  field: PathInfo
                  operator: matches
                  type: string
                  values:
                    - /post
              - expression:
                  field: ContentType
                  operator: equals
                  type: string
                  values:
                    - application/json
          id: d6317646-2f99-4bee-b344-aedc5a34f387
          id_selector: null
          operation: REDACT
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: VOLATILE
          transformer: JSON_PATH
          transformer_config:
            - $.card-security-code
          transformer_config_map: null
          type: null
      host_endpoint: (.*)\.verygoodproxy\.com
      id: b7f49dec-71e5-4f88-8a8c-3ada0c242db4
      ordinal: null
      port: 80
      protocol: http
      source_endpoint: '*'
      tags:
        name: echo.apps.verygood.systems-navajo-white-cylinder
        source: RouteContainer
      updated_at: '2023-01-17T17:59:59'
    id: b7f49dec-71e5-4f88-8a8c-3ada0c242db4
    type: rule_chain
version: 1
